server/routes/web.php
<?php


use App\Http\Controllers\Web\Auth\LoginController;
use App\Http\Controllers\Web\Auth\RegisterController;
use App\Http\Controllers\Web\WelcomeController;

Route::namespace('Web')->group(function () {

    // TODO удалит
    Route::get('/test', [WelcomeController::class, 'test']);
    Route::get('/', [WelcomeController::class, 'index'])->name('home');

    # Auth
    Route::namespace('Auth')->group(function () {

        # Вход todo вынести в api
        Route::get('login', [LoginController::class, 'show'])->name('login');
        Route::post('login', [LoginController::class, 'login'])->name('login');

        # Выход
        Route::post('logout', [LoginController::class, 'logout'])->name('logout');

        # По токену
        //  get('/verify/{token}', 'RegisterController@verify')->name('register.verify');

        # Сбросить пароль
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'ResetPasswordController@reset');

        # Регистрация
        Route::prefix('register')->name('register.')->group(function () {
            Route::get('/', [RegisterController::class, 'register_form'])->name('form');
            Route::post('/', [RegisterController::class, 'register_ajax'])->name('send');
//                get('account_type', [RegisterController::class, 'getRegisterAccountType'])->name('account_type.form');
//                post('account_type', [RegisterController::class, 'postRegisterAccountType'])->name('account_type');
        });
    });
});


//Route::get('/home', 'HomeController@index')->name('home');

// TODO PARSER
//Route::get('/parser', 'ParserController@index')->name('parser');

# По токену (мыло + срок жизни)
//get('auth/token/{token}', 'AuthenticationController@token')->name('token');

# Profiles
Route::group([
    'prefix'     => 'profiles',
    'as'         => 'profiles.',
    'namespace'  => 'Profiles',
    'middleware' => ['auth:web'],
], function () {

    Route::group([
        'prefix'     => 'settings',
        'as'         => 'settings.',
        'namespace'  => 'Settings',
        'middleware' => ['auth:web'],
    ], function () {
        Route::get('/', 'SettingsController@index')->name('home');
        Route::put('/update', 'SettingsController@update')->name('update');
        Route::get('/email', 'SettingsController@email')->name('email');
        Route::get('/password', 'SettingsController@password')->name('password');
    });


    Route::group([
        'namespace' => 'Company',
        'prefix'    => 'company',
        'as'        => 'company.',
    ], function () {

        # Форма редактирование данных компании
        Route::get('/{username}', 'HomeController')
            ->name('home')
            ->where('username', '[a-zA-Z0-9_-]+');

        # редактирование данных компании
        Route::post('/edit/{username}', 'EditController')
            ->name('edit')
            ->where('username', '[a-zA-Z0-9_-]+');

        Route::post('/avatar/{id}', 'AvatarController')
            ->name('avatar');


        Route::group([
            'namespace' => 'Product',
            'prefix'    => 'product',
            'as'        => 'product.',
        ], function () {
            Route::get('/add', 'CreateController@form')->name('add');
            Route::post('/save', 'CreateController@save')->name('save');
        });

    });


//    group([
//        'namespace' => 'Company',
//        'prefix'    => 'company',
//        'as'        => 'company.',
//    ], function () {
//        get('/', 'ProfileController@index')->name('home');
//        // get('/{id}', 'ProfileController@show')->name('show');
////        get('/edit', 'ProfileController@edit')->name('edit');
//        put('/update', 'ProfileController@update')->name('update');
//
//    });

});


# ADMIN
Route::group(
    [
        'prefix'     => 'admin',
        'as'         => 'admin.',
        'namespace'  => 'Admin',
        'middleware' => ['auth', 'can:admin-panel'],
    ],
    function () {

        Route::get('/', 'HomeController@index')->name('dashboard');

        Route::get('/activities', 'ActivityController@index')->name('activities');
        // user
        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController');

        Route::resource('pages', 'PagesController');

        Route::group(['prefix' => 'pages/{page}', 'as' => 'pages.'], function () {
            Route::post('/first', 'PagesController@first')->name('first');
            Route::post('/up', 'PagesController@up')->name('up');
            Route::post('/down', 'PagesController@down')->name('down');
            Route::post('/last', 'PagesController@last')->name('last');
        });

        Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');


        Route::resource('regions', 'RegionController');

        Route::group(['namespace' => 'Category',], function () {

            Route::resource('categories', 'CategoryController');

            Route::group(['prefix' => 'categories/{category}', 'as' => 'categories.'], function () {
                Route::post('/first', 'CategoryController@first')->name('first');
                Route::post('/up', 'CategoryController@up')->name('up');
                Route::post('/down', 'CategoryController@down')->name('down');
                Route::post('/last', 'CategoryController@last')->name('last');

                Route::resource('attributes', 'AttributeController');
                Route::resource('attributes.value', 'AttributeValueController');

            });
        });

    }
);


Route::group(['namespace' => 'Company'], function () {

    Route::group(['prefix' => 'suppliers', 'as' => 'suppliers.'], function () {

        # компании
        Route::get('/', 'SuppliersController@index')->name('list');
        Route::get('/{slug}', 'SuppliersController@show')->name('show');

        Route::get('/{company}/contact', 'SuppliersController@contact')->name('contact');
        Route::get('/{company}/product/{product}', 'SuppliersController@showGoods')->name('show-product');
        Route::get('/{company}/{category}', 'SuppliersController@category')->name('category');


    });

});

//TODO categoty праверка по slug родительских !!!

Route::group(['namespace' => 'Catalog'], function () {

    // product list
//    get('catalog/{category}', 'CategoriesController@show')
//        ->name('catalog')
//        ->where('category', '[a-zA-Z0-9/_-]+');

    // company list
    Route::get('/{category}/suppliers', 'CategoriesController@suppliers')
        ->name('catalog.suppliers')
        ->where('category', '[a-zA-Z0-9/_-]+');

//    get('/{category}/producer', 'CategoriesController@producer')
//        ->name('catalog.suppliers')
//        ->where('category', '[a-zA-Z0-9/_-]+');


});

#СООБЩИТЕ ПОСТАВЩИКАМ, ЧТО ВАМ НУЖНО
Route::group([
    'prefix' => 'tenders',
    'as'     => 'tenders.',
], function () {

});


Route::get('/search/result', 'SearchController@index');

//
Route::get('/{path}', 'Catalog\PathController')
    ->name('category')
    ->where('path', '[a-zA-Z0-9/_-]+');

server/app/Http/Controllers/Admin/Category/AttributeController.php
<?php

namespace App\Http\Controllers\Admin\Category;

use App\Domain\Catalog\Category\Attribute;
use App\Domain\Catalog\Category\Category;
use App\Http\Controllers\Controller;
use Breadcrumbs;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class AttributeController extends Controller
{
    public function __construct()
    {
        // $this->middleware('can:manage-adverts-categories');
    }

    public function create(Category $category)
    {
        $types = Attribute::getListType();

        Breadcrumbs::addHierarchyOfNeeds($category->getAncestors(), 'admin.categories.show' );
        Breadcrumbs::append($category->getName(), route('admin.categories.show', $category), false);
        Breadcrumbs::append('Attributes Create', null, true);

        return view('admin.categories.attributes.create', compact('category', 'types'));
    }

    public function store(Request $request, Category $category)
    {
        $this->validate($request, [
            'title'    => 'required|string|max:255',
            'slug'     => 'nullable|alpha_dash',
            'type'     => ['required', 'string', 'max:255', Rule::in(array_keys(Attribute::getListType()))],
            'required' => 'nullable|string|max:255',
        ]);

        $attribute = new Attribute();
        $attribute->setTitle($request['title']);
        $attribute->setSlug($request['slug'] ? $request['slug'] : str_slug($request['title']));
        $attribute->setType($request['type']);
        $attribute->setRequired((bool)$request['required']);

        $attribute = $category->attributes()->save($attribute);
        $attribute->fresh();


        return redirect()->route('admin.categories.attributes.show', [$category, $attribute]);
    }

    public function show(Category $category, Attribute $attribute)
    {
        return view('admin.categories.attributes.show', compact('category', 'attribute'));
    }

    public function edit(Category $category, Attribute $attribute)
    {
        $types = Attribute::getListType();

        return view('admin.categories.attributes.edit', compact('category', 'attribute', 'types'));
    }

    public function update(Request $request, Category $category, Attribute $attribute)
    {
        $this->validate($request, [
            'title'    => 'required|string|max:255',
            'slug'     => 'nullable|alpha_dash',
            'type'     => ['required', 'string', 'max:255', Rule::in(array_keys(Attribute::getListType()))],
            'required' => 'nullable|string|max:255',
        ]);

        $category->attributes()->findOrFail($attribute->id)->update([
            'title'    => $request['title'],
            'slug'     => $request['slug'] ? $request['slug'] : str_slug($request['title']),
            'type'     => $request['type'],
            'required' => (bool)$request['required'],
        ]);

        return redirect()->route('admin.categories.show', $category);
    }

    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('admin.categories.show', $category);
    }
}

server/app/Http/Controllers/Admin/Category/AttributeValueController.php
<?php

namespace App\Http\Controllers\Admin\Category;

use App\Domain\Catalog\Category\Attribute;
use App\Domain\Catalog\Category\AttributeValue;
use App\Domain\Catalog\Category\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class AttributeValueController extends Controller
{


    public function __construct()
    {
        // $this->middleware('can:manage-adverts-categories');
    }

    public function create(Category $category, Attribute $attribute)
    {
        return view('admin.categories.attributes.value.create', compact('category', 'attribute'));
    }

    public function store(Request $request, Category $category, Attribute $attribute)
    {
        $this->validate($request, [
            'title' => 'required|string|max:255',
            'slug'  => 'nullable|alpha_dash',
        ]);

        $value = new AttributeValue();

        $slug = $request['slug'] ? $request['slug'] : str_slug($request['title']);

        $value->setTitle($request['title']);
        $value->setSlug($slug);
        $value->setSku($attribute->getSlug() . '-' . $slug);

        $attribute->values()->save($value);
        $attribute->fresh();

        return redirect()->route('admin.categories.attributes.show', [$category, $attribute]);
    }

    public function edit(Category $category, Attribute $attribute, AttributeValue $value)
    {
        return view('admin.categories.attributes.value.edit', compact('category', 'attribute', 'value'));
    }

    public function update(Request $request, Category $category, Attribute $attribute, AttributeValue $value)
    {
        $this->validate($request, [
            'title' => 'required|string|max:255',
            'slug'  => 'nullable|alpha_dash',
        ]);

        $value = $attribute->getValues()->findOrFail($value->getId());

        $value->fill($request->all())->save();

        return redirect()->route('admin.categories.attributes.show', [$category, $attribute]);
    }

    public function destroy(Category $category, Attribute $attribute, AttributeValue $value)
    {
        $value->delete();

        return redirect()->route('admin.categories.attributes.show', [$category, $attribute]);
    }
}

server/app/Http/Controllers/Admin/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Category;

use App\Domain\Catalog\Category\Category;
use App\Http\Controllers\Controller;
use Breadcrumbs;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function __construct()
    {
      //  $this->middleware('can:manage-adverts-categories');
        Breadcrumbs::append('Categoryes', route('admin.categories.index'));
    }

    public function index()
    {
        $categories = Category::defaultOrder()->withDepth()->get();

        return view('admin.categories.index', compact('categories'));
    }

    public function create()
    {
        $parents = Category::defaultOrder()->withDepth()->get();

        return view('_admin.categories.create', compact('parents'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'slug' => 'alphadash|max:255',
            'parent' => 'nullable|integer|exists:categories,id',
        ]);

        $category = Category::create([
            'name'      => $request['name'],
            'slug'      => str_slug($request['slug']),
            'parent_id' => $request['parent'],
        ]);

        return redirect()->route('admin.categories.show', $category);
    }

    public function show(Category $category)
    {
        $parent_attributes = $category->parentAttributes();
        $attributes = $category->attributes()->get();

        Breadcrumbs::addHierarchyOfNeeds($category->getAncestors(), 'admin.categories.index');
        Breadcrumbs::append($category->getName(), null, true);

        return view('admin.categories.show', compact('category', 'attributes', 'parent_attributes'));
    }

    public function edit(Category $category)
    {
        $parents = Category::defaultOrder()->withDepth()->get();

        return view('admin.categories.edit', compact('category', 'parents'));
    }

    public function update(Request $request, Category $category)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'slug' => 'required|alphadash|max:255',
            'parent' => 'nullable|integer|exists:categories,id',
        ]);

        $category->update([
            'name' => $request['name'],
            'slug' => str_slug($request['slug']),
            'parent_id' => $request['parent'],
        ]);

        return redirect()->route('admin.categories.show', $category);
    }

    public function first(Category $category)
    {
        if ($first = $category->siblings()->defaultOrder()->first()) {
            $category->insertBeforeNode($first);
        }

        return redirect()->route('admin.categories.index');
    }

    public function up(Category $category)
    {
        $category->up();

        return redirect()->route('admin.categories.index');
    }

    public function down(Category $category)
    {
        $category->down();

        return redirect()->route('admin.categories.index');
    }

    public function last(Category $category)
    {
        if ($last = $category->siblings()->defaultOrder('desc')->first()) {
            $category->insertAfterNode($last);
        }

        return redirect()->route('admin.categories.index');
    }

    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('admin.categories.index');
    }
}

server/app/Http/Controllers/Api/CategoriesController.php
<?php

namespace App\Http\Controllers\Api;

use App\Domain\Catalog\Category\Category;
use App\Http\Controllers\Controller;
use App\Http\Resources\Product\AttributesResource;
use App\Http\Resources\Product\CatalogResource;
use App\Services\CategoryService;
use Illuminate\Http\Request;


class CategoriesController extends Controller
{

    /**
     * @var CategoryService
     */
    private $service;

    public function __construct(CategoryService $service)
    {

        $this->service = $service;
    }

    public function getAll()
    {
        return $category = Category::defaultOrder()->get()->toTree();
    }

    public function catalog(Request $request)
    {
        if($request->has('segment'))
        {
            $categoryes = $this->service->getChildrenByParentId($request->get('segment'));

            return CatalogResource::collection($categoryes);
        }

        return response()->json('error get catalog', 404);
    }

    public function features(Request $request)
    {
        if($request->has('category'))
        {
            $categoryes = $this->service->getFeatureList($request->get('category'));

            $features = AttributesResource::collection(collect($categoryes));

           return $features;
        }

        return response()->json('error get features', 404);
    }
}

server/resources/views/admin/categories/_form.blade.php
<img class="avatar" v-if="imgDataUrl" :src="imgDataUrl" v-show="true" style="display: none;">

{{--<img class="avatar" v-else="" width="200" height="200" alt="" src="{{ $user->profile->getAvatarUrl() }}">--}}


{{--<file-input filename="files[]" fileid="avatar" classname="hidde-new-file"></file-input>--}}



<div class="row">
    <div class="fileinput">
        <div class="fileinput__block">
            <div class="fileinput__button" @click="toggleShow">
                <span><i class="fa fa-pencil" aria-hidden="true"></i>Изменить</span>
            </div>
        </div>
        <my-upload field="avatar"
                   @crop-success="cropSuccess"
                   @crop-upload-success="cropUploadSuccess"
                   @crop-upload-fail="cropUploadFail"
                   v-model="show_crop"
                   :width="200"
                   :height="200"
                   lang-type="ru"
                   url="/cabinet/profile/avatar"
                   :params="params"
                   :headers="headers"
                   img-format="png">

        </my-upload>
    </div>
</div>

<div class="row">
    <div class="col">
        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                   name="name"
                   value="{{ old('name', $category->name) }}"
                   required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label for="slug" class="col-form-label">Slug</label>
            <input id="slug" type="text"
                   class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}"
                   name="slug"
                   value="{{ old('slug', $category->slug) }}" required>
            @if ($errors->has('slug'))
                <span class="invalid-feedback"><strong>{{ $errors->first('slug') }}</strong></span>
            @endif
        </div>
    </div>
</div>

<div class="form-group">
    <label for="parent" class="col-form-label">Parent</label>
    <select id="parent" class="form-control{{ $errors->has('parent') ? ' is-invalid' : '' }}" name="parent">
        <option value=""></option>
        @foreach ($parents as $parent)
            <option value="{{ $parent->id }}"{{ $parent->id == old('parent', $category->parent_id) ? ' selected' : '' }}>
                @for ($i = 0; $i < $parent->depth; $i++) &mdash; @endfor
                {{ $parent->name }}
            </option>
        @endforeach;
    </select>
    @if ($errors->has('parent'))
        <span class="invalid-feedback"><strong>{{ $errors->first('parent') }}</strong></span>
    @endif
</div>

{{--<div class="form-group">--}}
    {{--<button type="submit" class="btn btn-primary">Save</button>--}}
{{--</div>--}}

server/resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('content')

    <form method="POST" action="{{ route('admin.categories.store') }}">
        @csrf

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="slug" class="col-form-label">Slug</label>
            <input id="slug" type="text" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}" name="slug" value="{{ old('slug') }}" required>
            @if ($errors->has('slug'))
                <span class="invalid-feedback"><strong>{{ $errors->first('slug') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="parent" class="col-form-label">Parent</label>
            <select id="parent" class="form-control{{ $errors->has('parent') ? ' is-invalid' : '' }}" name="parent">
                <option value=""></option>
                @foreach ($parents as $parent)
                    <option value="{{ $parent->id }}"{{ $parent->id == old('parent') ? ' selected' : '' }}>
                        @for ($i = 0; $i < $parent->depth; $i++) &mdash; @endfor
                        {{ $parent->name }}
                    </option>
                @endforeach;
            </select>
            @if ($errors->has('parent'))
                <span class="invalid-feedback"><strong>{{ $errors->first('parent') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

server/resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div id="pages" class="page-layout simple tabbed">

        <!-- HEADER -->
    @include('admin.includes._page-header' , [
        'title' => 'Edit Category',
        'back_link' => route('admin.categories.index'),
        'logo' => null,
      ])
    <!-- / HEADER -->

        <!-- CONTENT -->
        <div class="page-content">

            <div class="card p-6">
                <form method="POST" action="{{ route('admin.categories.update', $category) }}">
                    @csrf
                    @method('PUT')

                    @include('admin.categories._form')

                </form>
            </div>
        </div>
        <!-- / CONTENT -->
    </div>

@endsection

@section('scripts')
@endsection

server/resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="page-layout carded full-width">

        <div class="top-bg bg-primary text-auto"></div>

        <!-- CONTENT -->
        <div class="page-content-wrapper">

            <form>
                <!-- HEADER -->
            @include('admin.includes._table-header', [
                'title' => __('Сатегории'),
                'total' => $categories->count(),
                'add_url' => route('admin.categories.index')
            ])
            <!-- / HEADER -->
            </form>

            <div class="page-content-card">

                <div class="toolbar p-6">Content Toolbar</div>

                <div class="page-content custom-scrollbar">

                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Slug</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach ($categories as $category)
                            <tr>
                                <td>
                                    @for ($i = 0; $i < $category->depth; $i++) &mdash; @endfor
                                    <a href="{{ route('admin.categories.show', $category) }}">{{ $category->name }}</a>
                                </td>
                                <td>{{ $category->slug }}</td>
                                <td>
                                    <div class="d-flex flex-row">

                                        @include('admin.includes._list_sortable', ['route' => 'categories', 'model' => $category])

                                    </div>
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>


            </div>

           {{-- <nav aria-label="pagination" class="my-8">
                {{$categories->links()}}
            </nav>--}}
        </div>
        <!-- / CONTENT -->
    </div>

@endsection

server/resources/views/admin/categories/show.blade.php
@extends('layouts.admin')

@section('content')
    <div id="pages" class="page-layout simple tabbed">

        <!-- HEADER -->
    @include('admin.includes._page-header' , [
        'title' => 'Category '. $category->name,
        'back_link' => route('admin.categories.index'),
        'logo' => null,
      ])
    <!-- / HEADER -->

        <!-- CONTENT -->
        <div class="page-content">

            <div class="card p-6">
                <div class="d-flex flex-row mb-3">
                    <a href="{{ route('admin.categories.create') }}" class="btn btn-success">Add Category</a>
                    <a href="{{ route('admin.categories.edit', $category) }}" class="btn btn-primary mr-1">Edit</a>
                    <form method="POST" action="{{ route('admin.categories.destroy', $category) }}" class="mr-1">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger">Delete</button>
                    </form>
                </div>

                <table class="table table-bordered table-striped">
                    <tbody>
                    <tr>
                        <th>ID</th>
                        <td>{{ $category->id }}</td>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <td>{{ $category->name }}</td>
                    </tr>
                    <tr>
                        <th>Slug</th>
                        <td>{{ $category->slug }}</td>
                    </tr>
                    <tbody>
                    </tbody>
                </table>

                <p><a href="{{ route('admin.categories.attributes.create', $category) }}" class="btn btn-success">Add
                        Attribute</a></p>

                @include('admin.categories.attributes._list', [$parent_attributes, $attributes])

            </div>
        </div>
        <!-- / CONTENT -->
    </div>

@endsection

@section('scripts')
@endsection