server/routes/web.php
<?php


use App\Http\Controllers\Web\Auth\LoginController;
use App\Http\Controllers\Web\Auth\RegisterController;
use App\Http\Controllers\Web\WelcomeController;

Route::namespace('Web')->group(function () {

    // TODO удалит
    Route::get('/test', [WelcomeController::class, 'test']);
    Route::get('/', [WelcomeController::class, 'index'])->name('home');

    # Auth
    Route::namespace('Auth')->group(function () {

        # Вход todo вынести в api
        Route::get('login', [LoginController::class, 'show'])->name('login');
        Route::post('login', [LoginController::class, 'login'])->name('login');

        # Выход
        Route::post('logout', [LoginController::class, 'logout'])->name('logout');

        # По токену
        //  get('/verify/{token}', 'RegisterController@verify')->name('register.verify');

        # Сбросить пароль
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'ResetPasswordController@reset');

        # Регистрация
        Route::prefix('register')->name('register.')->group(function () {
            Route::get('/', [RegisterController::class, 'register_form'])->name('form');
            Route::post('/', [RegisterController::class, 'register_ajax'])->name('send');
//                get('account_type', [RegisterController::class, 'getRegisterAccountType'])->name('account_type.form');
//                post('account_type', [RegisterController::class, 'postRegisterAccountType'])->name('account_type');
        });
    });
});


//Route::get('/home', 'HomeController@index')->name('home');

// TODO PARSER
//Route::get('/parser', 'ParserController@index')->name('parser');

# По токену (мыло + срок жизни)
//get('auth/token/{token}', 'AuthenticationController@token')->name('token');

# Profiles
Route::group([
    'prefix'     => 'profiles',
    'as'         => 'profiles.',
    'namespace'  => 'Profiles',
    'middleware' => ['auth:web'],
], function () {

    Route::group([
        'prefix'     => 'settings',
        'as'         => 'settings.',
        'namespace'  => 'Settings',
        'middleware' => ['auth:web'],
    ], function () {
        Route::get('/', 'SettingsController@index')->name('home');
        Route::put('/update', 'SettingsController@update')->name('update');
        Route::get('/email', 'SettingsController@email')->name('email');
        Route::get('/password', 'SettingsController@password')->name('password');
    });


    Route::group([
        'namespace' => 'Company',
        'prefix'    => 'company',
        'as'        => 'company.',
    ], function () {

        # Форма редактирование данных компании
        Route::get('/{username}', 'HomeController')
            ->name('home')
            ->where('username', '[a-zA-Z0-9_-]+');

        # редактирование данных компании
        Route::post('/edit/{username}', 'EditController')
            ->name('edit')
            ->where('username', '[a-zA-Z0-9_-]+');

        Route::post('/avatar/{id}', 'AvatarController')
            ->name('avatar');


        Route::group([
            'namespace' => 'Product',
            'prefix'    => 'product',
            'as'        => 'product.',
        ], function () {
            Route::get('/add', 'CreateController@form')->name('add');
            Route::post('/save', 'CreateController@save')->name('save');
        });

    });


//    group([
//        'namespace' => 'Company',
//        'prefix'    => 'company',
//        'as'        => 'company.',
//    ], function () {
//        get('/', 'ProfileController@index')->name('home');
//        // get('/{id}', 'ProfileController@show')->name('show');
////        get('/edit', 'ProfileController@edit')->name('edit');
//        put('/update', 'ProfileController@update')->name('update');
//
//    });

});


# ADMIN
Route::group(
    [
        'prefix'     => 'admin',
        'as'         => 'admin.',
        'namespace'  => 'Admin',
        'middleware' => ['auth', 'can:admin-panel'],
    ],
    function () {

        Route::get('/', 'HomeController@index')->name('dashboard');

        Route::get('/activities', 'ActivityController@index')->name('activities');
        // user
        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController');

        Route::resource('pages', 'PagesController');

        Route::group(['prefix' => 'pages/{page}', 'as' => 'pages.'], function () {
            Route::post('/first', 'PagesController@first')->name('first');
            Route::post('/up', 'PagesController@up')->name('up');
            Route::post('/down', 'PagesController@down')->name('down');
            Route::post('/last', 'PagesController@last')->name('last');
        });

        Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');


        Route::resource('regions', 'RegionController');

        Route::group(['namespace' => 'Category',], function () {

            Route::resource('categories', 'CategoryController');

            Route::group(['prefix' => 'categories/{category}', 'as' => 'categories.'], function () {
                Route::post('/first', 'CategoryController@first')->name('first');
                Route::post('/up', 'CategoryController@up')->name('up');
                Route::post('/down', 'CategoryController@down')->name('down');
                Route::post('/last', 'CategoryController@last')->name('last');

                Route::resource('attributes', 'AttributeController');
                Route::resource('attributes.value', 'AttributeValueController');

            });
        });

    }
);


Route::group(['namespace' => 'Company'], function () {

    Route::group(['prefix' => 'suppliers', 'as' => 'suppliers.'], function () {

        # компании
        Route::get('/', 'SuppliersController@index')->name('list');
        Route::get('/{slug}', 'SuppliersController@show')->name('show');

        Route::get('/{company}/contact', 'SuppliersController@contact')->name('contact');
        Route::get('/{company}/product/{product}', 'SuppliersController@showGoods')->name('show-product');
        Route::get('/{company}/{category}', 'SuppliersController@category')->name('category');


    });

});

//TODO categoty праверка по slug родительских !!!

Route::group(['namespace' => 'Catalog'], function () {

    // product list
//    get('catalog/{category}', 'CategoriesController@show')
//        ->name('catalog')
//        ->where('category', '[a-zA-Z0-9/_-]+');

    // company list
    Route::get('/{category}/suppliers', 'CategoriesController@suppliers')
        ->name('catalog.suppliers')
        ->where('category', '[a-zA-Z0-9/_-]+');

//    get('/{category}/producer', 'CategoriesController@producer')
//        ->name('catalog.suppliers')
//        ->where('category', '[a-zA-Z0-9/_-]+');


});

#СООБЩИТЕ ПОСТАВЩИКАМ, ЧТО ВАМ НУЖНО
Route::group([
    'prefix' => 'tenders',
    'as'     => 'tenders.',
], function () {

});


Route::get('/search/result', 'SearchController@index');

//
Route::get('/{path}', 'Catalog\PathController')
    ->name('category')
    ->where('path', '[a-zA-Z0-9/_-]+');

server/app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Domain\User\Enums\UserStateEnum;
use App\Domain\User\Role;
use App\Domain\User\User;
use App\Http\Requests\Admin\Users\CreateRequest;
use App\Http\Requests\Admin\Users\UpdateRequest;
use App\Http\Controllers\Controller;
use App\Services\UserService;
use App\UseCases\Auth\RegisterService;
use Illuminate\Http\Request;

class UsersController extends Controller
{

    /**
     * @var UserService
     */
    private $service;

    public function __construct(UserService $service)
    {
        $this->service = $service;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $query = (new User)->with('profile')->orderByDesc('id');

        if (!empty($value = $request->get('id'))) {
            $query->where('id', $value);
        }

        if (!empty($value = $request->get('name'))) {
            $query->where('username', 'like', '%' . $value . '%');
        }

        if (!empty($value = $request->get('email'))) {
            $query->where('email', 'like', '%' . $value . '%');
        }

        if (!empty($value = $request->get('status'))) {
            $query->where('state', $value);
        }

        if (!empty($value = $request->get('role'))) {
            $query->where('role', $value);
        }

        $users = $query->paginate(20);

        $statuses = UserStateEnum::toArray();

        $roles = Role::getRoleList();

        return view('admin.users.index', compact('users', 'statuses', 'roles'));
    }

    public function create()
    {
        return view('admin.users.create');
    }

    public function store(CreateRequest $request)
    {
        $user = User::new(
            $request['username'],
            $request['email']
        );

        return redirect()->route('admin.users.show', $user);
    }

    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    public function edit(User $user)
    {
        $roles = Role::getRoleList();

        return view('admin.users.edit', compact('user', 'roles'));
    }

    public function update(UpdateRequest $request, User $user)
    {
        $this->service->update($request->only(['name', 'email']));

        if ($request['role'] !== $user->role) {
            $user->changeRole($request['role']);
        }

        return redirect()->route('admin.users.show', $user);
    }

    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('admin.users.index');
    }

    public function verify(User $user)
    {
        $this->register->verify($user->id);

        return redirect()->route('admin.users.show', $user);
    }
}

server/resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')

    <form method="POST" action="{{ route('admin.users.store') }}">
        @csrf

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="email" class="col-form-label">E-Mail Address</label>
            <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>
            @if ($errors->has('email'))
                <span class="invalid-feedback"><strong>{{ $errors->first('email') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

server/resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')

    <form method="POST" action="{{ route('admin.users.update', $user) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="username" class="col-form-label">Name</label>
            <input id="username" class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" name="username" value="{{ old('username', $user->username) }}" required>
            @if ($errors->has('username'))
                <span class="invalid-feedback"><strong>{{ $errors->first('username') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="email" class="col-form-label">E-Mail Address</label>
            <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email', $user->email) }}" required>
            @if ($errors->has('email'))
                <span class="invalid-feedback"><strong>{{ $errors->first('email') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="role" class="col-form-label">Role</label>
            <select id="role" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="role">
                @foreach ($roles as $value => $label)
                    <option value="{{ $value }}"{{ $value === old('role', $user->role) ? ' selected' : '' }}>{{ $label }}</option>
                @endforeach;
            </select>
            @if ($errors->has('role'))
                <span class="invalid-feedback"><strong>{{ $errors->first('role') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

server/resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')


    <div class="page-layout carded full-width">

        <div class="top-bg bg-primary text-auto"></div>

        <!-- CONTENT -->
        <div class="page-content-wrapper">

            <form>
                <!-- HEADER -->
            @include('admin.includes._table-header', [
                'title' => __('Users'),
                'total' => $users->total(),
                'add_url' => route('admin.users.create')
            ])
{{--                <p><a href="{{ route('admin.users.create') }}" class="btn btn-success">Add User</a></p>--}}

                <!-- / HEADER -->
            </form>

            <div class="card mb-3">
                <div class="card-header">Filter</div>
                <div class="card-body">
                    <form action="?" method="GET">
                        <div class="row">
                            <div class="col-sm-1">
                                <div class="form-group">
                                    <label for="id" class="col-form-label">ID</label>
                                    <input id="id" class="form-control" name="id" value="{{ request('id') }}">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label for="username" class="col-form-label">Username</label>
                                    <input id="username" class="form-control" name="username" value="{{ request('username') }}">
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label for="email" class="col-form-label">Email</label>
                                    <input id="email" class="form-control" name="email" value="{{ request('email') }}">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label for="state" class="col-form-label">Status</label>
                                    <select id="state" class="form-control" name="state">
                                        <option value=""></option>
                                        @foreach ($statuses as $value => $label)
                                            <option value="{{ $value }}"{{ $value === request('state') ? ' selected' : '' }}>{{ $label }}</option>
                                        @endforeach;
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label for="role" class="col-form-label">Role</label>
                                    <select id="role" class="form-control" name="role">
                                        <option value=""></option>
                                        @foreach ($roles as $value => $label)
                                            <option value="{{ $value }}"{{ $value === request('role') ? ' selected' : '' }}>{{ $label }}</option>
                                        @endforeach;
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="col-form-label">&nbsp;</label><br />
                                    <button type="submit" class="btn btn-primary">Search</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="page-content-card">

                <div class="toolbar p-6">Content Toolbar</div>

                <div class="page-content custom-scrollbar">

                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Role</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach ($users as $user)
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td><a href="{{ route('admin.users.show', $user) }}">{{ $user->username }}</a></td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    @if ($user->isWait())
                                        <span class="badge badge-secondary">Waiting</span>
                                    @endif
                                    @if ($user->isActive())
                                        <span class="badge badge-primary">Active</span>
                                    @endif
                                </td>
                                <td>
                                    @if ($user->isAdmin())
                                        <span class="badge badge-danger">Admin</span>

                                    @elseif($user->isModerator())
                                        <span class="badge badge-warning">Moderator</span>
                                    @else
                                        @foreach($user->getRole() as $role)
                                            @if($role->getName())
                                                <span class="badge badge-secondary">{{$role->getName()}}</span>
                                            @endif
                                        @endforeach
                                    @endif
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>


                </div>
                <nav aria-label="pagination" class="my-8">
                    {{ $users->links() }}
                </nav>
            </div>


        </div>
        <!-- / CONTENT -->
    </div>




@endsection

server/resources/views/admin/users/show.blade.php
@extends('layouts.admin')

@section('content')

    <div class="d-flex flex-row mb-3">
        <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-primary mr-1">Edit</a>

        @if ($user->isWait())
            <form method="POST" action="{{ route('admin.users.verify', $user) }}" class="mr-1">
                @csrf
                <button class="btn btn-success">Verify</button>
            </form>
        @endif

        <form method="POST" action="{{ route('admin.users.destroy', $user) }}" class="mr-1">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger">Delete</button>
        </form>
    </div>

    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th>ID</th><td>{{ $user->id }}</td>
        </tr>
        <tr>
            <th>Name</th><td>{{ $user->username }}</td>
        </tr>
        <tr>
            <th>Email</th><td>{{ $user->email }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>
                @if ($user->isWait())
                    <span class="badge badge-secondary">Waiting</span>
                @endif
                @if ($user->isActive())
                    <span class="badge badge-primary">Active</span>
                @endif
            </td>
        </tr>
        <tr>
            <th>Role</th>
            <td>
                @if ($user->isAdmin())
                    <span class="badge badge-danger">Admin</span>
                @else
                    <span class="badge badge-secondary">User</span>
                @endif
            </td>
        </tr>
        <tbody>
        </tbody>
    </table>
@endsection