server/routes/web.php
<?php


use App\Http\Controllers\Web\Auth\LoginController;
use App\Http\Controllers\Web\Auth\RegisterController;
use App\Http\Controllers\Web\WelcomeController;

Route::namespace('Web')->group(function () {

    // TODO удалит
    Route::get('/test', [WelcomeController::class, 'test']);
    Route::get('/', [WelcomeController::class, 'index'])->name('home');

    # Auth
    Route::namespace('Auth')->group(function () {

        # Вход todo вынести в api
        Route::get('login', [LoginController::class, 'show'])->name('login');
        Route::post('login', [LoginController::class, 'login'])->name('login');

        # Выход
        Route::post('logout', [LoginController::class, 'logout'])->name('logout');

        # По токену
        //  get('/verify/{token}', 'RegisterController@verify')->name('register.verify');

        # Сбросить пароль
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'ResetPasswordController@reset');

        # Регистрация
        Route::prefix('register')->name('register.')->group(function () {
            Route::get('/', [RegisterController::class, 'register_form'])->name('form');
            Route::post('/', [RegisterController::class, 'register_ajax'])->name('send');
//                get('account_type', [RegisterController::class, 'getRegisterAccountType'])->name('account_type.form');
//                post('account_type', [RegisterController::class, 'postRegisterAccountType'])->name('account_type');
        });
    });
});


//Route::get('/home', 'HomeController@index')->name('home');

// TODO PARSER
//Route::get('/parser', 'ParserController@index')->name('parser');

# По токену (мыло + срок жизни)
//get('auth/token/{token}', 'AuthenticationController@token')->name('token');

# Profiles
Route::group([
    'prefix'     => 'profiles',
    'as'         => 'profiles.',
    'namespace'  => 'Profiles',
    'middleware' => ['auth:web'],
], function () {

    Route::group([
        'prefix'     => 'settings',
        'as'         => 'settings.',
        'namespace'  => 'Settings',
        'middleware' => ['auth:web'],
    ], function () {
        Route::get('/', 'SettingsController@index')->name('home');
        Route::put('/update', 'SettingsController@update')->name('update');
        Route::get('/email', 'SettingsController@email')->name('email');
        Route::get('/password', 'SettingsController@password')->name('password');
    });


    Route::group([
        'namespace' => 'Company',
        'prefix'    => 'company',
        'as'        => 'company.',
    ], function () {

        # Форма редактирование данных компании
        Route::get('/{username}', 'HomeController')
            ->name('home')
            ->where('username', '[a-zA-Z0-9_-]+');

        # редактирование данных компании
        Route::post('/edit/{username}', 'EditController')
            ->name('edit')
            ->where('username', '[a-zA-Z0-9_-]+');

        Route::post('/avatar/{id}', 'AvatarController')
            ->name('avatar');


        Route::group([
            'namespace' => 'Product',
            'prefix'    => 'product',
            'as'        => 'product.',
        ], function () {
            Route::get('/add', 'CreateController@form')->name('add');
            Route::post('/save', 'CreateController@save')->name('save');
        });

    });


//    group([
//        'namespace' => 'Company',
//        'prefix'    => 'company',
//        'as'        => 'company.',
//    ], function () {
//        get('/', 'ProfileController@index')->name('home');
//        // get('/{id}', 'ProfileController@show')->name('show');
////        get('/edit', 'ProfileController@edit')->name('edit');
//        put('/update', 'ProfileController@update')->name('update');
//
//    });

});


# ADMIN
Route::group(
    [
        'prefix'     => 'admin',
        'as'         => 'admin.',
        'namespace'  => 'Admin',
        'middleware' => ['auth', 'can:admin-panel'],
    ],
    function () {

        Route::get('/', 'HomeController@index')->name('dashboard');

        Route::get('/activities', 'ActivityController@index')->name('activities');
        // user
        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController');

        Route::resource('pages', 'PagesController');

        Route::group(['prefix' => 'pages/{page}', 'as' => 'pages.'], function () {
            Route::post('/first', 'PagesController@first')->name('first');
            Route::post('/up', 'PagesController@up')->name('up');
            Route::post('/down', 'PagesController@down')->name('down');
            Route::post('/last', 'PagesController@last')->name('last');
        });

        Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');


        Route::resource('regions', 'RegionController');

        Route::group(['namespace' => 'Category',], function () {

            Route::resource('categories', 'CategoryController');

            Route::group(['prefix' => 'categories/{category}', 'as' => 'categories.'], function () {
                Route::post('/first', 'CategoryController@first')->name('first');
                Route::post('/up', 'CategoryController@up')->name('up');
                Route::post('/down', 'CategoryController@down')->name('down');
                Route::post('/last', 'CategoryController@last')->name('last');

                Route::resource('attributes', 'AttributeController');
                Route::resource('attributes.value', 'AttributeValueController');

            });
        });

    }
);


Route::group(['namespace' => 'Company'], function () {

    Route::group(['prefix' => 'suppliers', 'as' => 'suppliers.'], function () {

        # компании
        Route::get('/', 'SuppliersController@index')->name('list');
        Route::get('/{slug}', 'SuppliersController@show')->name('show');

        Route::get('/{company}/contact', 'SuppliersController@contact')->name('contact');
        Route::get('/{company}/product/{product}', 'SuppliersController@showGoods')->name('show-product');
        Route::get('/{company}/{category}', 'SuppliersController@category')->name('category');


    });

});

//TODO categoty праверка по slug родительских !!!

Route::group(['namespace' => 'Catalog'], function () {

    // product list
//    get('catalog/{category}', 'CategoriesController@show')
//        ->name('catalog')
//        ->where('category', '[a-zA-Z0-9/_-]+');

    // company list
    Route::get('/{category}/suppliers', 'CategoriesController@suppliers')
        ->name('catalog.suppliers')
        ->where('category', '[a-zA-Z0-9/_-]+');

//    get('/{category}/producer', 'CategoriesController@producer')
//        ->name('catalog.suppliers')
//        ->where('category', '[a-zA-Z0-9/_-]+');


});

#СООБЩИТЕ ПОСТАВЩИКАМ, ЧТО ВАМ НУЖНО
Route::group([
    'prefix' => 'tenders',
    'as'     => 'tenders.',
], function () {

});


Route::get('/search/result', 'SearchController@index');

//
Route::get('/{path}', 'Catalog\PathController')
    ->name('category')
    ->where('path', '[a-zA-Z0-9/_-]+');

server/app/Http/Controllers/Api/ProfileController.php
<?php

namespace App\Http\Controllers\Api;

use App\Domain\User\Profile;
use App\Domain\User\User;
use App\Http\Controllers\Controller;
use App\Transformers\ActivityTransformer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class ProfileController extends Controller
{
    public function avatar(Request $request)
    {
        if ($request->hasFile('avatar')) {

            /** @var User $user */
            $user = auth()->user();

            $file = $request->file('avatar')->store('avatar');

            dd(\Auth::user());

            $profile = new Profile;
            $profile->setAvatar($file);



            if($user->profile()->save($profile))
            {
                return response(['files' => $file]);
            }
            return response('lll');
        }



    }
}

server/app/Http/Controllers/Profiles/Company/AvatarController.php
<?php

namespace App\Http\Controllers\Profiles\Company;


use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class AvatarController extends Controller
{
    public function __invoke(Request $request, $username)
    {
        $company = auth()->user()->getCompany();

        return view('profiles.company.home', compact('company'));
    }


}

server/app/Http/Controllers/Profiles/Company/EditController.php
<?php

namespace App\Http\Controllers\Profiles\Company;


use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class EditController extends Controller
{
    public function __invoke(Request $request, $username)
    {
        $company = auth()->user()->getCompany();

        return view('profiles.company.home', compact('company'));
    }



}

server/app/Http/Controllers/Profiles/Company/HomeController.php
<?php

namespace App\Http\Controllers\Profiles\Company;

use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function __invoke($username)
    {
        $company = auth()->user()->getCompany();

//        dd($company);

        return view('profiles.company.home', compact('company'));
    }



}

server/app/Http/Controllers/Profiles/Company/Product/CreateController.php
<?php

namespace App\Http\Controllers\Profiles\Company\Product;


use App\Domain\User\User;
use App\Http\Controllers\Controller;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class CreateController extends Controller
{

    /**
     * @var CategoryService
     */
    private $service;

    public function __construct(CategoryService $service)
    {
        $this->middleware('can:manage-own-product');

        $this->service = $service;

    }

    public function form()
    {
        //$this->checkAccess(auth()->user());

        $segment = $this->service->getChildrenSelfRoot();

        return view('profiles.company.product.index', compact('segment'));
    }

    public function save(Request $request)
    {
        dd($request->all());
    }

//    private function checkAccess(User $user): void
//    {
//        if (!Gate::allows('manage-own-product', $user)) {
//            abort(403);
//        }
//    }

}

server/app/Http/Controllers/Profiles/Settings/SettingsController.php
<?php

namespace App\Http\Controllers\Profiles\Settings;

use App\Domain\User\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Cabinet\ProfileEditRequest;
use App\UseCases\Profile\ProfileService;
use Illuminate\Http\Request;

class SettingsController extends Controller
{
    private $service;

    public function __construct(ProfileService $service)
    {
        $this->service = $service;
    }

    public function index()
    {
        return view('profiles.settings.home');
    }

    /**
     * @param ProfileEditRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ProfileEditRequest $request)
    {
        try {
            $this->service->edit(auth()->id(), $request->getDto());

        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }
        return redirect()->route('cabinet.profile.home');
    }

    public function email()
    {
        return view('profiles.settings.email');
    }

    public function password()
    {
        return view('profiles.settings.password');
    }


    /**
     * TODO вынести в отдельный класс
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Symfony\Component\HttpFoundation\Response
     */
    public function avatar(Request $request)
{
    if ($request->hasFile('avatar')) {

        /** @var User $user */
        $user = auth()->user();

        $file = Storage::disk('avatar')->putFile(' / ', $request->file('avatar'));

        if ($user->profile()->update([
            'avatar' => $file,
        ])) {
            return response(['files' => $file]);
        }
        return response('lll');
    }


}
}

server/resources/views/profiles/profile/_block-info.blade.php
<div class="text-center">
    <div class="text-center vert-space">

        <img class="avatar" v-if="imgDataUrl" :src="imgDataUrl" v-show="true" style="display: none;">

        <img class="avatar" v-else="" width="200" height="200" alt="" src="{{ $user->profile->getAvatarUrl() }}">


        {{--<file-input filename="files[]" fileid="avatar" classname="hidde-new-file"></file-input>--}}

        <div class="fileinput">
            <div class="fileinput__block">
                <div class="fileinput__button" @click="toggleShow">
                    <span><i class="fa fa-pencil" aria-hidden="true"></i>Изменить</span>
                </div>
            </div>
            <my-upload field="avatar"
                       @crop-success="cropSuccess"
                       @crop-upload-success="cropUploadSuccess"
                       @crop-upload-fail="cropUploadFail"
                       v-model="show_crop"
                       :width="200"
                       :height="200"
                       lang-type="ru"
                       url="/cabinet/profile/avatar"
                       :params="params"
                       :headers="headers"
                       img-format="png">

            </my-upload>
        </div>


        {{--<file-management :settings="{{ json_encode($props) }}"></file-management>--}}
        {{--<input type="file" id="img-uploader-btn-1">--}}
    </div>
</div>

server/resources/views/profiles/profile/_form.blade.php
<form method="POST" action="{{ route('profiles.settings.update') }}">
    @csrf
    @method('PUT')

    <div class="form-group">
        <label for="username" class="col-form-label">Username</label>
        <input id="username"
               type="text"
               class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}"
               name="username"
               value="{{ old('username', $user->username) }}"
               required>
        @if ($errors->has('username'))
            <span class="invalid-feedback"><strong>{{ $errors->first('username') }}</strong></span>
        @endif
    </div>

    <div class="form-group">
        <label for="email" class="col-form-label">Email</label>
        <input id="email"
               type="email"
               class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
               name="email"
               value="{{ old('email', $user->email) }}" required>
        @if ($errors->has('email'))
            <span class="invalid-feedback"><strong>{{ $errors->first('email') }}</strong></span>
        @endif
    </div>

    <div class="form-group">
        <label for="first_name" class="col-form-label">First Name</label>
        <input id="first_name"
               type="text"
               class="form-control{{ $errors->has('first_name') ? ' is-invalid' : '' }}"
               name="first_name"
               value="{{ old('first_name', $user->first_name) }}">
        @if ($errors->has('first_name'))
            <span class="invalid-feedback"><strong>{{ $errors->first('first_name') }}</strong></span>
        @endif
    </div>

    <div class="form-group">
        <label for="last_name" class="col-form-label">Last Name</label>
        <input id="last_name"
               type="text"
               class="form-control{{ $errors->has('last_name') ? ' is-invalid' : '' }}"
               name="last_name"
               value="{{ old('last_name', $user->last_name) }}">
        @if ($errors->has('last_name'))
            <span class="invalid-feedback"><strong>{{ $errors->first('last_name') }}</strong></span>
        @endif
    </div>

    <div class="form-group">
        <label for="phone" class="col-form-label">Phone</label>
        <input id="phone"
               type="tel"
               class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}"
               name="phone"
               value="{{ old('phone', $user->phone) }}"
               required>
        @if ($errors->has('phone'))
            <span class="invalid-feedback"><strong>{{ $errors->first('phone') }}</strong></span>
        @endif
    </div>

    <div class="form-group">
        <label for="country" class="col-form-label">Country</label>
        <input id="country"
               type="text"
               class="form-control{{ $errors->has('country') ? ' is-invalid' : '' }}"
               name="country"
               value="{{ old('country', $user->country) }}">
        @if ($errors->has('country'))
            <span class="invalid-feedback"><strong>{{ $errors->first('country') }}</strong></span>
        @endif
    </div>

    <div class="form-group">
        <label for="city" class="col-form-label">City</label>
        <input id="city"
               type="text"
               class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}"
               name="city"
               value="{{ old('city', $user->city) }}">
        @if ($errors->has('city'))
            <span class="invalid-feedback"><strong>{{ $errors->first('city') }}</strong></span>
        @endif
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

server/resources/views/profiles/profile/home.blade.php
<div class="col-md-9">
    <div class="card">
        <div class="card__head">
            <div class="card__title">
                {{--<a class="link-black" href="#/settings/user_list">--}}
                {{--<i class="fa fa-arrow-left" aria-hidden="true"></i>--}}
                {{--</a>--}}
                Редактирование профиля
            </div>
        </div>
        <div class="card__content">
            <div class="row">
                <div class="col-md-4">
                    @include('cabinet.profile._block-info')
                </div>
                <div class="col-md-8">
                    @include('cabinet.profile._form')
                </div>
            </div>

        </div>
    </div>
</div>

server/resources/views/profiles/profile/phone.blade.php
@extends('layouts.app')

@section('content')
    @include('cabinet.profile._nav')

    <form method="POST" action="{{ route('cabinet.profile.phone.verify') }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="token" class="col-form-label">SMS Code</label>
            <input id="token" class="form-control{{ $errors->has('token') ? ' is-invalid' : '' }}" name="token" value="{{ old('token') }}" required>
            @if ($errors->has('token'))
                <span class="invalid-feedback"><strong>{{ $errors->first('token') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Verify</button>
        </div>
    </form>
@endsection