server/routes/web.php
<?php


use App\Http\Controllers\Web\Auth\LoginController;
use App\Http\Controllers\Web\Auth\RegisterController;
use App\Http\Controllers\Web\WelcomeController;

Route::namespace('Web')->group(function () {

    // TODO удалит
    Route::get('/test', [WelcomeController::class, 'test']);
    Route::get('/', [WelcomeController::class, 'index'])->name('home');

    # Auth
    Route::namespace('Auth')->group(function () {

        # Вход todo вынести в api
        Route::get('login', [LoginController::class, 'show'])->name('login');
        Route::post('login', [LoginController::class, 'login'])->name('login');

        # Выход
        Route::post('logout', [LoginController::class, 'logout'])->name('logout');

        # По токену
        //  get('/verify/{token}', 'RegisterController@verify')->name('register.verify');

        # Сбросить пароль
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'ResetPasswordController@reset');

        # Регистрация
        Route::prefix('register')->name('register.')->group(function () {
            Route::get('/', [RegisterController::class, 'register_form'])->name('form');
            Route::post('/', [RegisterController::class, 'register_ajax'])->name('send');
//                get('account_type', [RegisterController::class, 'getRegisterAccountType'])->name('account_type.form');
//                post('account_type', [RegisterController::class, 'postRegisterAccountType'])->name('account_type');
        });
    });
});


//Route::get('/home', 'HomeController@index')->name('home');

// TODO PARSER
//Route::get('/parser', 'ParserController@index')->name('parser');

# По токену (мыло + срок жизни)
//get('auth/token/{token}', 'AuthenticationController@token')->name('token');

# Profiles
Route::group([
    'prefix'     => 'profiles',
    'as'         => 'profiles.',
    'namespace'  => 'Profiles',
    'middleware' => ['auth:web'],
], function () {

    Route::group([
        'prefix'     => 'settings',
        'as'         => 'settings.',
        'namespace'  => 'Settings',
        'middleware' => ['auth:web'],
    ], function () {
        Route::get('/', 'SettingsController@index')->name('home');
        Route::put('/update', 'SettingsController@update')->name('update');
        Route::get('/email', 'SettingsController@email')->name('email');
        Route::get('/password', 'SettingsController@password')->name('password');
    });


    Route::group([
        'namespace' => 'Company',
        'prefix'    => 'company',
        'as'        => 'company.',
    ], function () {

        # Форма редактирование данных компании
        Route::get('/{username}', 'HomeController')
            ->name('home')
            ->where('username', '[a-zA-Z0-9_-]+');

        # редактирование данных компании
        Route::post('/edit/{username}', 'EditController')
            ->name('edit')
            ->where('username', '[a-zA-Z0-9_-]+');

        Route::post('/avatar/{id}', 'AvatarController')
            ->name('avatar');


        Route::group([
            'namespace' => 'Product',
            'prefix'    => 'product',
            'as'        => 'product.',
        ], function () {
            Route::get('/add', 'CreateController@form')->name('add');
            Route::post('/save', 'CreateController@save')->name('save');
        });

    });


//    group([
//        'namespace' => 'Company',
//        'prefix'    => 'company',
//        'as'        => 'company.',
//    ], function () {
//        get('/', 'ProfileController@index')->name('home');
//        // get('/{id}', 'ProfileController@show')->name('show');
////        get('/edit', 'ProfileController@edit')->name('edit');
//        put('/update', 'ProfileController@update')->name('update');
//
//    });

});


# ADMIN
Route::group(
    [
        'prefix'     => 'admin',
        'as'         => 'admin.',
        'namespace'  => 'Admin',
        'middleware' => ['auth', 'can:admin-panel'],
    ],
    function () {

        Route::get('/', 'HomeController@index')->name('dashboard');

        Route::get('/activities', 'ActivityController@index')->name('activities');
        // user
        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController');

        Route::resource('pages', 'PagesController');

        Route::group(['prefix' => 'pages/{page}', 'as' => 'pages.'], function () {
            Route::post('/first', 'PagesController@first')->name('first');
            Route::post('/up', 'PagesController@up')->name('up');
            Route::post('/down', 'PagesController@down')->name('down');
            Route::post('/last', 'PagesController@last')->name('last');
        });

        Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');


        Route::resource('regions', 'RegionController');

        Route::group(['namespace' => 'Category',], function () {

            Route::resource('categories', 'CategoryController');

            Route::group(['prefix' => 'categories/{category}', 'as' => 'categories.'], function () {
                Route::post('/first', 'CategoryController@first')->name('first');
                Route::post('/up', 'CategoryController@up')->name('up');
                Route::post('/down', 'CategoryController@down')->name('down');
                Route::post('/last', 'CategoryController@last')->name('last');

                Route::resource('attributes', 'AttributeController');
                Route::resource('attributes.value', 'AttributeValueController');

            });
        });

    }
);


Route::group(['namespace' => 'Company'], function () {

    Route::group(['prefix' => 'suppliers', 'as' => 'suppliers.'], function () {

        # компании
        Route::get('/', 'SuppliersController@index')->name('list');
        Route::get('/{slug}', 'SuppliersController@show')->name('show');

        Route::get('/{company}/contact', 'SuppliersController@contact')->name('contact');
        Route::get('/{company}/product/{product}', 'SuppliersController@showGoods')->name('show-product');
        Route::get('/{company}/{category}', 'SuppliersController@category')->name('category');


    });

});

//TODO categoty праверка по slug родительских !!!

Route::group(['namespace' => 'Catalog'], function () {

    // product list
//    get('catalog/{category}', 'CategoriesController@show')
//        ->name('catalog')
//        ->where('category', '[a-zA-Z0-9/_-]+');

    // company list
    Route::get('/{category}/suppliers', 'CategoriesController@suppliers')
        ->name('catalog.suppliers')
        ->where('category', '[a-zA-Z0-9/_-]+');

//    get('/{category}/producer', 'CategoriesController@producer')
//        ->name('catalog.suppliers')
//        ->where('category', '[a-zA-Z0-9/_-]+');


});

#СООБЩИТЕ ПОСТАВЩИКАМ, ЧТО ВАМ НУЖНО
Route::group([
    'prefix' => 'tenders',
    'as'     => 'tenders.',
], function () {

});


Route::get('/search/result', 'SearchController@index');

//
Route::get('/{path}', 'Catalog\PathController')
    ->name('category')
    ->where('path', '[a-zA-Z0-9/_-]+');

server/resources/views/admin/pages/_form.blade.php
<div class="form-row">
    <div class="form-group col-md-6">
        <label for="category_id" class="col-form-label">Category</label>
        <select @change="changeTitlePage"
                id="category_id"
                class="form-control{{ $errors->has('category_id') ? ' is-invalid' : '' }}"
                name="category_id">
            <option value=""></option>
            @foreach ($categories as $category)
                <optgroup label="{{ $category->name }}">
                    @foreach($category->children as $item)
                        @if(isset($page->category_id))
                            <option value="{{ $item->id }}"{{ $item->id == old('category_id', $page->category_id) ? ' selected' : '' }}>
                                {{ $item->name }}
                            </option>
                        @else
                            <option value="{{ $item->id }}"{{ $item->id == old('category_id') ? ' selected' : '' }}>
                                {{ $item->name }}
                            </option>
                        @endif
                    @endforeach
                </optgroup>
            @endforeach;
        </select>
        @if ($errors->has('category_id'))
            <span class="invalid-feedback"><strong>{{ $errors->first('category_id') }}</strong></span>
        @endif
    </div>

    <div class="form-group col-md-6">
        <input id="title"
               type="text"
               class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}"
               name="title" :value="titleSelected"
               value="{{ isset($page->title) ?  old('title', $page->title) : old('title') }}">
        @if ($errors->has('title'))
            <span class="invalid-feedback"><strong>{{ $errors->first('title') }}</strong></span>
        @endif
        <label for="title" class="col-form-label">Title</label>
    </div>

</div>

<div class="form-group">
    <textarea id="content" rows="4" name="content"
              class="form-control">{{ isset($page->content) ? old('content', $page->content) : old('content')}}</textarea>
    @if ($errors->has('content'))
        <span class="invalid-feedback"><strong>{{ $errors->first('content') }}</strong></span>
    @endif
    <label for="content" class="col-form-label">Текст страницы</label>
</div>


<hr>

<fieldset class="form-group border-success">
    <legend class="text-success" align="center">SEO</legend>

    <hr>

    <div class="form-row">
        <div class="col-md-6">
            <div class="form-group">
                <textarea id="meta_description" rows="4" name="meta_description" class="form-control">
                    {{ isset($page->meta_description) ? old('meta_description', $page->meta_description) : old('meta_description')}}
                </textarea>
                @if ($errors->has('meta_description'))
                    <span class="invalid-feedback"><strong>{{ $errors->first('meta_description') }}</strong></span>
                @endif
                <label for="meta_description" class="col-form-label">Описание</label>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <textarea id="meta_keywords" :value="titleSelected" rows="4" name="meta_keywords" class="form-control">
                    {{ isset($page->meta_keywords)? old('meta_keywords', $page->meta_keywords) : old('meta_keywords')}}
                </textarea>
                @if ($errors->has('meta_keywords'))
                    <span class="invalid-feedback"><strong>{{ $errors->first('meta_keywords') }}</strong></span>
                @endif
                <label for="meta_keywords" class="col-form-label">Ключевые слова</label>
            </div>
        </div>
    </div>

    <div class="form-row">

        @if(isset($page->enabled))
            <input type="checkbox" ref="cb" name="enabled" class="js-switch"
                   @if( old('enabled', $page->enabled)) checked @endif />
        @else
            <input type="checkbox" ref="cb" :checked="pages.enabled" @change="pages.enabled = $event.target.checked"
                   name="enabled" class="js-switch" @if( old('enabled')) checked @endif />
        @endif

    </div>

</fieldset>

server/resources/views/admin/pages/create.blade.php
@extends('layouts.admin')

@section('content')
    <div id="pages" class="page-layout simple tabbed">

        <!-- HEADER -->
    @include('admin.includes._page-header' , [
        'title' => 'New Page',
        'back_link' => route('admin.pages.index'),
        'logo' => null,
      ])
    <!-- / HEADER -->

        <!-- CONTENT -->
        <div class="page-content">

            <ul class="nav nav-tabs" id="myTab" role="tablist">

                <li class="nav-item">
                    <a class="nav-link btn active"
                       id="basic-info-tab"
                       data-toggle="tab"
                       href="#basic-info-tab-pane"
                       role="tab"
                       aria-controls="basic-info-tab-pane"
                       aria-expanded="true">Базовая информация</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link btn"
                       id="product-images-tab"
                       data-toggle="tab"
                       href="#product-images-tab-pane"
                       role="tab"
                       aria-controls="product-images-tab-pane">Скриншоты</a>
                </li>

            </ul>

            <div class="tab-content">

                <div class="tab-pane fade show active" id="basic-info-tab-pane" role="tabpanel"
                     aria-labelledby="basic-info-tab">
                    <div class="card p-6">
                        <form id="form_save" method="POST" action="{{route('admin.pages.store')}}">
                            @csrf
                            @include('admin.pages._form')
                        </form>
                    </div>
                </div>

                <div class="tab-pane fade" id="product-images-tab-pane" role="tabpanel"
                     aria-labelledby="product-images-tab">

                    <div class="card p-6">
                        <div class="row">
                            <div class="alert alert-success" role="alert">
                                <h4 class="alert-heading">Сохраните базовую информацию клиента!</h4>
                                <p>Чтобы загрузить логотип нужно сначала сохранить клиента</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!-- / CONTENT -->
    </div>

@endsection

@section('scripts')
@endsection

server/resources/views/admin/pages/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="page-layout carded full-width">

        <div class="top-bg bg-primary text-auto"></div>

        <!-- CONTENT -->
        <div class="page-content-wrapper">

            <form>
                <!-- HEADER -->
            @include('admin.includes._table-header', [
                'title' => __('Страницы'),
                'total' => $pages->total(),
                'add_url' => route('admin.pages.create')
            ])
            <!-- / HEADER -->
            </form>

            <div class="page-content-card">

                <div class="toolbar p-6">Content Toolbar</div>

                <div class="page-content custom-scrollbar">

                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <?php $columns = [
                                'id'   => 'ID',
                                'category_id' => 'Категория',
                                'name' => 'Название',
                                'path' => 'Ссылка',
                                'sort' => 'Сорт',
                                'enabled' => 'Статус'
                            ]; ?>

                            @foreach($columns as $k => $v)
                                <th class="d-md-table-cell">
                                    <a class="fuse-ripple-ready" style="text-decoration: none" href="{{route('admin.pages.index',  http_build_query([
                                        'order'  => $k,
                                        'dir'    => $order == $k ? !$dir : $dir
                                    ]))}}">
                                        {{$v}}

                                        @if ($order != $k)
                                            <i class="icon icon-sort font-seze-10"></i>
                                        @elseif ($dir)
                                            <i class="icon icon-sort-descending"></i>
                                        @else
                                            <i class="icon icon-sort-ascending"></i>
                                        @endif

                                    </a>
                                </th>
                            @endforeach

                            <th class="d-md-table-cell">
                                Порядок
                            </th>
                            <th class="d-md-table-cell">
                                <span class="fuse-ripple-ready">Управление</span>
                            </th>
                        </tr>
                        </thead>
                        <tbody>

                        @if($pages)

                            @foreach($pages as $page)
                            <tr>
                                {{--<th scope="row">{{$loop->iteration}}</th>--}}
                                <th scope="row">{{$page->id}}</th>
                                <td>
                                    @if($page->category)
                                    <a href="{{route('admin.categories.show', $page->category)}}">{{$page->category->name}}</a>
                                    @endif
                                </td>
                                {{--<td><img src="{{ $page->getLogo()}}" alt="" width="40" class="img-thumbnail img-fluid"></td>--}}
                                <td>{{$page->title}}</td>
                                <td>
                                    @if($page->path)
                                        <a href="{{$page->path}}" target="_blank">{{$page->path}}</a>
                                    @endif
                                </td>
                                <td>{{$page->sort}}</td>
                                <td>
                                    @if(!$page->isEnabled())
                                        <i class="icon-clock-fast text-muted" title="черновик"></i>
                                    @else
                                        <i class="icon-checkbox-marked-circle text-success" title="активен"></i>
                                    @endif
                                </td>
                                <td>
                                    <div class="d-flex flex-row">

                                      @include('admin.includes._list_sortable', ['route' => 'pages', 'model' => $page])
                                    </div>
                                </td>
                                <td>

                                    <a href="{{route('admin.pages.edit', $page)}}" class="btn btn-icon fuse-ripple-ready"
                                       aria-label="Customer details">
                                        <i class="icon icon-pencil s-4"></i>
                                    </a>

                                    {{--<a @click.prevent="confirmDelete({text:'Вы уверены что хотите удалить портфолио: {{$page->name}}?', url:'{{ route("admin.pages.destroy", $page) }}'})"--}}
                                       {{--class="btn btn-icon fuse-ripple-ready"--}}
                                       {{--aria-label="Customer delete"><i class="icon s-4 icon-delete"></i>--}}
                                    {{--</a>--}}

                                </td>
                            </tr>
                        @endforeach

                        @endif
                        </tbody>
                    </table>

                </div>


            </div>

            <nav aria-label="pagination" class="my-8">
                {{$pages->links()}}
            </nav>
        </div>
        <!-- / CONTENT -->
    </div>

@endsection